alias leopard='ssh leopard -t "zsh -c \"tmux a -d\""'
alias lion='ssh lion -t "zsh -c \"tmux a -d\""'
alias dragon='ssh dragon -t "zsh -c \"tmux a -d\""'
alias docktrench='ssh docktrench -t "zsh -c \"tmux a -d\""'

alias mount_leopard='sshfs -o reconnect,ServerAliveInterval=5,ServerAliveCountMax=1,follow_symlinks leopard: ~/leopard'
alias mount_lion='sshfs -o reconnect,ServerAliveInterval=5,ServerAliveCountMax=1,follow_symlinks lion: ~/lion'
alias mount_dragon='sshfs -o reconnect,ServerAliveInterval=5,ServerAliveCountMax=1,follow_symlinks dragon: ~/dragon'
alias mount_docktrench='sshfs -o reconnect,ServerAliveInterval=5,ServerAliveCountMax=1,follow_symlinks docktrench: ~/docktrench'
alias mount_all='mount_leopard && mount_lion && mount_dragon && mount_docktrench'
