#!/usr/bin/env bash
polution=$(echo "$(curl --compressed -s --header "apikey: $AIRLY_API_KEY" 'https://airapi.airly.eu/v2/measurements/installation?indexType=AIRLY_CAQI&installationId=9914' | jq -r '.current.values[] | select(.name == "PM25") | .value')/25 * 100" | bc -l)
polution=$(echo "$polution/1" | bc)
echo "$polution% "
