#!/usr/bin/env bash
echo "pm2.5 $(printf "%.0d" $(echo "$(curl --compressed -s --header "apikey: $AIRLY_API_KEY" 'https://airapi.airly.eu/v2/measurements/installation?indexType=AIRLY_CAQI&installationId=228' | jq -r '.current.values[] | select(.name == "PM25") | .value')/25 * 100" | bc -l))%"
