#!/usr/bin/env perl

## The sink we are interested in should be given as the
## 1st argument to the script.
my $sink=$ARGV[0];# || die("Need a sink number as the first argument\n");

## Run the pactl command and save the output in
## ther filehandle $fh
open(my $fh, '-|', 'pactl list sinks');

## Set the record separator to consecutive newlines (same as -000)
## this means we read the info for each sink as a single "line".
$/="\n\n";

## Go through the pactl output
while (<$fh>) {
    ## If this is the sink we are interested in
    if (/#$sink/) {
        ## Extract the current colume of this sink
        /Volume:.*?(\d+)%/;
        my $volume=$1;
        /Mute: (\w+)/;
        my $mute=$1;

        if ($mute eq "yes") {
          print "";
        }
        else {
          print " $volume%\n";
        }
    }
}
